# name: Bare Minimum Requirements

# on: [push, pull_request, git_add, git_commit_-m, git_push_origin_reference]

# jobs:
#   job1:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - name: test before deployment
#         uses: actions/setup-node@v1
#         with:
#           node-version: '16'
#       - run: npm install
#       - run: npm test
#   job2:
#     runs-on: ubuntu-latest
#     name: Auto Deploy
#     needs: job1
#     steps:
#       - run: git add .
#       - run: git commit -m "Auto Deploy"
#       - run: git push origin reference




name: Test Automation practice

on:
  push:
    branches: ['reference']
  pull_request:
    branches: ['reference']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bare Minimum Requirements
        uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: npm install
      - run: npm run test
  build:
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm install
      - run: npm run test
      - run: npm run build --if-present

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm ci
      - run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
