name: Bare Minimum Requirements

on: [push, pull_request,build, test]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test before deployment
        uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: npm install
      - run: npm test
  job2:
    runs-on: ubuntu-latest
    name: Auto Deploy
    needs: job1
    steps:
      - uses: actions/checkout@v2
      - name: npm run build
        uses: actions/setup-node@v1
        with:
          node-version: '16'
        - run: npm run build
